name: Auto YAPF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapf
    - name: Formatting the code
      run: |
        yapf --style '{based_on_style: google, column_limit: 120, allow_multiline_lambdas: True}' --recursive --in-place .
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git diff --quiet && git diff --staged --quiet || git commit -am 'Auto YAPF with Google python style' && git push
