name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine toml
    
    - name: Update pyproject.toml version
      env:
        TAG_NAME: ${{ github.ref_name }}
      run: python -c 'import toml; f=open("pyproject.toml","r"); config=toml.load(f); config["project"]["version"]="${{ env.TAG_NAME }}"; open("pyproject.toml","w").write(toml.dumps(config))'
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: python -m twine upload dist/*
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body: https://pypi.org/project/stream-translator-gpt/${{ github.ref_name }}/